name: Build and Deploy Jekyll

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: false   # 캐시 자동 설치 끄고, 아래에서 수동 실행

      - name: Fix Gemfile.lock platform (Linux)
        run: |
          if [ -f Gemfile.lock ]; then
            bundle lock --add-platform x86_64-linux || true
          fi

      - name: Bundle install
        run: bundle install --jobs 4

      - name: Build with Jekyll
        run: bundle exec jekyll build -d _site

      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
